name: Fetch and Merge EPG Channel Info

on:
  workflow_dispatch:  # Allows manual triggering of this workflow
  schedule:
    - cron: '0 6,18 * * *'  # Runs at 6:00 AM and 6:00 PM UTC (1:00 AM and 1:00 PM ET)

concurrency:
  group: epg-fetch-merge
  cancel-in-progress: true

jobs:
  channel-fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'  # Use the latest LTS version of Node.js

      - name: Install dependencies
        run: |
          npm install  # Install dependencies defined in package.json

      - name: Fetch EPG channel data and merge into XML
        run: |
          echo "Fetching and merging EPG channel data..."
          npm run grab -- --channels=./scripts/_epg-start/channels-test-start.xml --output=./scripts/_epg-end/merged-epg.xml
          
          # You can also use the following if it's part of your script:
          # npx tsx scripts/commands/epg/grab.ts --channels=./scripts/_epg-start/channels-test-start.xml --output=./scripts/_epg-end/merged-epg.xml
          
          # Handle errors if necessary
          if [ $? -ne 0 ]; then
            echo "Error fetching or merging EPG data."
            exit 1
          fi

      - name: Force add and commit merged EPG file (always commit)
        run: |
          git config --global user.name "kyleabrahams"
          git config --global user.email "kyleagbc@gmail.com"
          
          # Force add the merged file even if no changes are detected
          git add -f ./scripts/_epg-end/merged-epg.xml
          
          # Force commit changes (if any)
          git commit --allow-empty -m "Auto commit: Merged EPG data on $(date)"
          
          # Push the changes to the repository
          git push origin main
