name: Delete Old Workflows

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Failed Workflows
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 10
          delete_run_by_conclusion: failure
