name: Dummy EPG XML

on:
  push:  # Runs when there is a commit to the main branch
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install pytz

      - name: List Files Before EPG Script
        run: |
          echo "Listing files in _epg-end directory before script run:"
          ls -la scripts/_epg-end/
          
          # List files tracked by git before removing
          echo "Listing files tracked by git in _epg-end directory:"
          git ls-files scripts/_epg-end/

      - name: Run EPG Script
        run: |
          python3 scripts/dummy_epg.py

      - name: List Files After EPG Script
        run: |
          echo "Listing files in _epg-end directory after script run:"
          ls -la scripts/_epg-end/

          # Check if old EPG files are tracked, and if so, remove them
          echo "Removing old EPG files from Git repository..."
          OLD_FILES=$(git ls-files scripts/_epg-end/dummy--epg---*.xml)
          if [ -n "$OLD_FILES" ]; then
              # Remove the old EPG files safely (handle spaces and special characters)
              echo "$OLD_FILES" | xargs -I {} git rm -f "{}"
              echo "✅ Old EPG files removed: $OLD_FILES"
          else
              echo "❌ No old EPG files found to remove."
          fi

          # Now create the new file
          python3 scripts/dummy_epg.py

          echo "Listing files in _epg-end directory after script run:"
          ls -la scripts/_epg-end/

          echo "Searching for new EPG file..."
          NEW_FILE=$(find scripts/_epg-end/ -name 'dummy--epg---*.xml' -print -quit)

          echo "Found file: $NEW_FILE"  # Debugging line to print found file name

          if [ -n "$NEW_FILE" ]; then
              echo "✅ New EPG file exists: $NEW_FILE"
              git config --global user.name "github-actions[bot]"
              git config --global user.email "github-actions[bot]@users.noreply.github.com"
              git add "$NEW_FILE"
              git commit -m "Updated EPG file: $NEW_FILE"
              git push origin main
              echo "✅ Successfully pushed the new EPG file!"
          else
              echo "❌ ERROR: New EPG file not found!"
              exit 1
          fi  # Close the if block here
