name: Dummy EPG XML

on:
  push:  # Runs when there is a commit to the main branch
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install pytz

      - name: List Files Before EPG Script
        run: |
          echo "Listing files in _epg-end directory before script run:"
          ls -la scripts/_epg-end/

      - name: Run EPG Script
        run: python3 scripts/dummy_epg.py

      - name: List Files After EPG Script
        run: |
          echo "Listing files in _epg-end directory before script run:"
          ls -la scripts/_epg-end/

          # Delete old EPG files from the repository
          echo "Removing old EPG files from Git repository..."
          git rm -f scripts/_epg-end/dummy--epg---*.xml

          # Now create the new file
          python3 scripts/dummy_epg.py

          echo "Listing files in _epg-end directory after script run:"
          ls -la scripts/_epg-end/

          echo "Searching for new EPG file..."
          NEW_FILE=$(find scripts/_epg-end/ -name 'dummy--epg---*.xml' -print -quit)

          echo "Found file: $NEW_FILE"  # Debugging line to print found file name

          if [ -n "$NEW_FILE" ]; then
              echo "✅ New EPG file exists: $NEW_FILE"
              git config --global user.name "github-actions[bot]"
              git config --global user.email "github-actions[bot]@users.noreply.github.com"
              git add "$NEW_FILE"
              git commit -m "Updated EPG file: $NEW_FILE"
              git push origin main
              echo "✅ Successfully pushed the new EPG file!"
          else
              echo "❌ ERROR: New EPG file not found!"
              exit 1
          fi
