name: Dummy EPG XML

on:
  push:  # Runs when there is a commit to the main branch
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install pytz

      - name: Run EPG Script
        run: python3 scripts/dummy_epg.py  # Updated path to match your repo structure

      - name: Upload Generated EPG File
        uses: actions/upload-artifact@v4
        with:
          name: epg-xml
          path: scripts/www/dummy-epg-*.xml  # Adjusted to match your repository file location
