name: Dummy EPG XML

on:
  schedule:
    - cron: '55 5 * * *'  # 12:55 AM ET every day (UTC-5)
    - cron: '55 17 * * *'  # 12:55 PM ET every day (UTC-5)

  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install pytz

      - name: List Files Before Cleanup
        run: |
          echo "Listing files in _epg-end directory before cleanup:"
          ls -la scripts/_epg-end/

      - name: Remove Old EPG Files
        run: |
          echo "Removing old EPG files..."
          find scripts/_epg-end/ -name 'dummy--epg---*.xml' -exec git rm -f {} \;
          echo "✅ Old EPG files removed."

      - name: Run EPG Script
        run: |
          echo "Generating new EPG file..."
          python3 scripts/dummy_epg.py

      - name: List Files After EPG Script
        run: |
          echo "Listing files in _epg-end directory after script run:"
          ls -la scripts/_epg-end/

      - name: Commit and Push Changes
        run: |
          NEW_FILE=$(find scripts/_epg-end/ -name 'dummy--epg---*.xml' -print -quit)

          if [ -n "$NEW_FILE" ]; then
              echo "✅ New EPG file found: $NEW_FILE"
              git config --global user.name "github-actions[bot]"
              git config --global user.email "github-actions[bot]@users.noreply.github.com"
              
              # Get current UTC time and convert it to Eastern Time
              ET_TIME=$(TZ="America/Toronto" date +"%b %d, %Y %I:%M:%S %p ET")

              git add "$NEW_FILE"
              git commit -m "Updated dummy epg file at $ET_TIME"
              git push origin main
              echo "✅ Successfully pushed the new EPG file!"
          else
              echo "❌ ERROR: New EPG file not found!"
              exit 1
          fi

