name: Notify on Workflow Completion

on:
  workflow_run:
    workflows: ["Scheduled Task"]  # Name of the original workflow
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          # Your email configuration settings here
          server_address: smtp.example.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          to: recipient@example.com
          subject: "GitHub Action Completed"
          body: "The scheduled task workflow has completed."
