name: Run Grab Command

on:
  push:
    branches:
      - main  # This will trigger on push to the main branch
      
on:
  schedule:
    - cron: '0 6 * * *'  # 1 AM ET every day UTC +5
    - cron: '0 18 * * *'  # 1 PM ET every day UTC +5

concurrency:
  group: "grab-command"
  cancel-in-progress: true  # If another instance is running, cancel it

jobs:
  run_grab:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0  # Ensures a full repo history for pushing

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Remove existing epg.xml
      run: rm -f $GITHUB_WORKSPACE/scripts/www/epg.xml

    - name: Combine XML files into epg.xml
      run: |
        echo "Combining XML files in the _epg-end directory into one..."
        
        # Set the output file path
        combined_file="$GITHUB_WORKSPACE/scripts/www/epg.xml"
        
        # Ensure the output directory exists
        mkdir -p $GITHUB_WORKSPACE/scripts/www/

        # Combine all XML files in _epg-end directory into one
        find $GITHUB_WORKSPACE/scripts/_epg-end/ -name '*.xml' -exec cat {} + > $combined_file
        
        echo "Combined XML files into: ${combined_file}"

    - name: Run grab command
      run: |
        output_file="$GITHUB_WORKSPACE/scripts/www/epg.xml"
        echo "Running grab command..."
        echo "Output file: ${output_file}"
        npm run grab -- --channels=$GITHUB_WORKSPACE/scripts/_epg-start/channels-test-start.xml --output=${output_file}
        echo "Grab command finished."

    - name: Verify file exists
      run: |
        if [ -f "$GITHUB_WORKSPACE/scripts/www/epg.xml" ]; then
          echo "✅ EPG file created successfully!"
        else
          echo "❌ ERROR: EPG file was not generated!"
          exit 1
        fi

    - name: Print current directory
      run: |
        echo "Current directory: $(pwd)"
        ls -la $GITHUB_WORKSPACE/scripts/www/

    - name: Check git status
      run: |
        echo "Checking git status..."
        git status

    - name: Commit and Push epg.xml
      run: |
        echo "Checking if epg.xml exists..."
        if [ -f "$GITHUB_WORKSPACE/scripts/www/epg.xml" ]; then
          echo "✅ EPG file exists. Preparing to commit and push..."

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Ensure Git detects changes
          git add -f $GITHUB_WORKSPACE/scripts/www/epg.xml
          git commit -m "Updated epg.xml [$(date)]" --allow-empty
          
          # Force push even if Git thinks there are no changes
          git push --force origin main
          
          echo "✅ Successfully pushed epg.xml to main!"
        else
          echo "❌ ERROR: epg.xml not found!"
          exit 1
        fi

    - name: Print absolute path of the file
      run: realpath $GITHUB_WORKSPACE/scripts/www/epg.xml || echo "File not found"
