name: Run Grab Command

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_grab:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Install missing module
      run: npm install @freearhey/core  # This ensures the missing module is installed

    - name: Run grab command
      run: |
        output_file="./scripts/www/epg-test.xml"
        echo "Output file: ${output_file}"
        npm run grab -- --channels=./scripts/_epg-start/channels-test-start.xml --output=${output_file}

    - name: Upload output file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: epg-output
        path: ./scripts/www/epg-test.xml

    - name: Commit changes
      run: |
        git add .
        git commit -m "Auto commit: EPG file updated on $(date)" || echo "No changes to commit"
        git push
