name: Run Grab Command

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_grab:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0  # Ensures a full repo history for pushing

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run grab command
      run: |
        output_file="./scripts/www/epg-test.xml"
        echo "Running grab command..."
        echo "Output file: ${output_file}"
        npm run grab -- --channels=./scripts/_epg-start/channels-test-start.xml --output=${output_file}
        echo "Grab command finished."

    - name: Verify file exists
      run: |
        if [ -f "./scripts/www/epg-test.xml" ]; then
          echo "✅ EPG file created successfully!"
        else
          echo "❌ ERROR: EPG file was not generated!"
          exit 1
        fi

    - name: Print current directory
      run: |
        echo "Current directory: $(pwd)"
        ls -la ./scripts/www/

    - name: Check git status
      run: |
        echo "Checking git status..."
        git status

    - name: Commit and Push epg-test.xml
      run: |
        echo "Checking if epg-test.xml exists..."
        if [ -f "./scripts/www/epg-test.xml" ]; then
          echo "✅ EPG file exists. Preparing to commit and push..."

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Stage the file (even if modified)
          git add -f ./scripts/www/epg-test.xml

          # Ensure Git detects changes
          if git diff --cached --quiet; then
            echo "⚠️ No actual changes detected in epg-test.xml. Skipping commit."
          else
            git commit -m "Updated epg-test.xml [$(date)]"
            git push origin main
            echo "✅ Successfully pushed epg-test.xml to main!"
          fi
        else
          echo "❌ ERROR: epg-test.xml not found!"
          exit 1
        fi

    - name: Print absolute path of the file
      run: realpath ./scripts/www/epg-test.xml || echo "File not found"
