name: Run Grab Command

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_grab:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run grab command
      run: |
        output_file="./scripts/www/epg-test.xml"
        echo "Running grab command..."
        echo "Output file: ${output_file}"
        npm run grab -- --channels=./scripts/_epg-start/channels-test-start.xml --output=${output_file}
        echo "Grab command finished."

    - name: Verify file exists
      run: |
        if [ -f "./scripts/www/epg-test.xml" ]; then
          echo "EPG file created successfully!"
        else
          echo "Error: EPG file was not generated!"
          exit 1
        fi

    - name: Print current directory
      run: |
        echo "Current directory: $(pwd)"
        ls -la

    - name: Check git status
      run: |
        echo "Checking git status..."
        git status -uall

    - name: Force Push epg-test.xml
      run: |
        echo "Checking if epg-test.xml exists"
        if [ -f "./scripts/www/epg-test.xml" ]; then
          echo "EPG file exists. Forcing commit and push..."
          
          git status # Show current git status
          git add ./scripts/www/epg-test.xml # Stage the file for commit
          git status # Show git status after adding
          git commit --allow-empty -m "Force push: epg-test.xml [$(date)]" # Commit the changes
          git status # Final git status to ensure the commit went through
          git push --force origin main # Force push the commit
        else
          echo "ERROR: epg-test.xml not found!"
          exit 1
        fi

    - name: Check Git configuration
      run: |
        echo "Git configuration:"
        git config --list

    - name: Print absolute path of the file
      run: |
        echo "Absolute path of epg-test.xml:"
        realpath ./scripts/www/epg-test.xml
