name: Run Grab Command

on:
  workflow_dispatch:  # Allow manual triggering
  schedule:
    - cron: '0 6 * * *'  # 1 AM ET every day UTC +5
    - cron: '0 18 * * *'  # 1 PM ET every day UTC +5

concurrency:
  group: "grab-command"
  cancel-in-progress: true  # If another instance is running, cancel it

jobs:
  run_grab:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout latest repository state
      uses: actions/checkout@v3
      with:
        ref: main  # Ensure it's the correct branch
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0  # Ensures a full repo history for pushing

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Remove existing epg.xml
      run: rm -f $GITHUB_WORKSPACE/scripts/www/epg.xml

    - name: Run grab command
      run: |
        output_file="$GITHUB_WORKSPACE/scripts/www/epg.xml"
        echo "Running grab command..."
        echo "Output file: ${output_file}"
        npm run grab -- --channels=./scripts/_epg-start/channels-custom-start.xml --output=${output_file}

    - name: Commit new epg.xml to repository
      run: |
        git config --global user.name "kyleabrahams"
        git config --global user.email "kyleagbc@gmail.com"
        git add $GITHUB_WORKSPACE/scripts/www/epg.xml
        git commit -m "Update epg.xml with latest grab command output"
        git push origin main
