name: Run Grab Command

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_grab:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run grab command
      run: |
        output_file="./scripts/www/epg-test.xml"
        echo "Output file: ${output_file}"
        npm run grab -- --channels=./scripts/_epg-start/channels-test-start.xml --output=${output_file}

    - name: Verify file exists
      run: |
        if [ -f "./scripts/www/epg-test.xml" ]; then
          echo "EPG file created successfully!"
        else
          echo "Error: EPG file was not generated!"
          exit 1
        fi

    - name: Upload output file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: epg-output
        path: ./scripts/www/epg-test.xml

    - name: Ensure epg-test.xml is updated and pushed
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        # Check if the file was actually created
        if [ ! -f "./scripts/www/epg-test.xml" ]; then
          echo "ERROR: epg-test.xml not found!"
          exit 1
        fi

        # Ensure Git detects the file change
        git add -f ./scripts/www/epg-test.xml

        # Commit and push the file
        git commit -m "Auto update: epg-test.xml [$(date)]" || echo "No changes detected, skipping commit"
        git push origin main || (echo "Push failed, retrying..." && git push --force origin main)
