name: Run Grab Command

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_grab:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run grab command
      run: |
        output_file="./scripts/www/epg-test.xml"
        echo "Output file: ${output_file}"
        npm run grab -- --channels=./scripts/_epg-start/channels-test-start.xml --output=${output_file}

    - name: Verify file exists
      run: |
        if [ -f "./scripts/www/epg-test.xml" ]; then
          echo "EPG file created successfully!"
        else
          echo "Error: EPG file was not generated!"
          exit 1
        fi

    - name: Upload output file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: epg-output
        path: ./scripts/www/epg-test.xml

    - name: Force Push epg-test.xml
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        if [ -f "./scripts/www/epg-test.xml" ]; then
          echo "EPG file exists. Forcing commit and push..."
          
          git add -f ./scripts/www/epg-test.xml
          git commit --allow-empty -m "Force push: epg-test.xml [$(date)]"
          git push --force origin main
        else
          echo "ERROR: epg-test.xml not found!"
          exit 1
        fi
