name: Run Grab Command

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'  # 1 AM every day
    - cron: '36 15 * * *' # 1 PM every day

jobs:
  run_grab:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0  # Ensures a full repo history for pushing

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Remove existing epg-test.xml
      run: rm -f $GITHUB_WORKSPACE/scripts/www/epg-test.xml

    - name: Run grab command
      run: |
        output_file="$GITHUB_WORKSPACE/scripts/www/epg-test.xml"
        echo "Running grab command..."
        echo "Output file: ${output_file}"
        npm run grab -- --channels=$GITHUB_WORKSPACE/scripts/_epg-start/channels-test-start.xml --output=${output_file}
        echo "Grab command finished."

    - name: Verify file exists
      run: |
        if [ -f "$GITHUB_WORKSPACE/scripts/www/epg-test.xml" ]; then
          echo "✅ EPG file created successfully!"
        else
          echo "❌ ERROR: EPG file was not generated!"
          exit 1
        fi

    - name: Print current directory
      run: |
        echo "Current directory: $(pwd)"
        ls -la $GITHUB_WORKSPACE/scripts/www/

    - name: Check git status
      run: |
        echo "Checking git status..."
        git status

    - name: Commit and Push epg-test.xml
      run: |
        echo "Checking if epg-test.xml exists..."
        if [ -f "$GITHUB_WORKSPACE/scripts/www/epg-test.xml" ]; then
          echo "✅ EPG file exists. Preparing to commit and push..."

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Ensure Git detects changes
          git add -f $GITHUB_WORKSPACE/scripts/www/epg-test.xml
          git commit -m "Updated epg-test.xml [$(date)]" --allow-empty
          
          # Force push even if Git thinks there are no changes
          git push --force origin main
          
          echo "✅ Successfully pushed epg-test.xml to main!"
        else
          echo "❌ ERROR: epg-test.xml not found!"
          exit 1
        fi

    - name: Print absolute path of the file
      run: realpath $GITHUB_WORKSPACE/scripts/www/epg-test.xml || echo "File not found"
