name: Scheduled Task
on:
  schedule:
    # This cron syntax runs at midnight UTC every day
    - cron: '10 5,17 * * *'  # 1:05 AM ET and 1:05 PM ET every day

jobs:
  scheduled_task:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install dependencies if required
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Run the script you want on the schedule
      - name: Navigate to correct directory and run Python script
        run: |
            # Make sure we are in the correct directory
            cd $GITHUB_WORKSPACE/scripts
            python3 merge_epg_cs.py update