name: EPG Scheduled Update

on:
  workflow_dispatch:  # Allows manual triggering of this workflow
  schedule:
    - cron: '37 7,19 * * *'  # Runs at 7:37 AM and 7:37 PM UTC (2:37 AM and 2:37 PM ET)

concurrency:
  group: epg-scheduled-task
  cancel-in-progress: true

jobs:
  scheduled_task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install requests  # Install the requests library

      - name: Install Node.js and npm dependencies
        run: |
          # Install Node.js (if not already installed by default)
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          # Install @freearhey/core and other dependencies
          npm install @freearhey/core
          npm install

      - name: Set Git user (if committing)
        run: |
          git config --global user.name "kyleabrahams"
          git config --global user.email "kyleagbc@gmail.com"

      - name: Install Python dependencies
        run: |
          if [ -f $GITHUB_WORKSPACE/scripts/requirements.txt ]; then
            pip install -r $GITHUB_WORKSPACE/scripts/requirements.txt
          else
            echo "No requirements.txt found"
          fi

      - name: Navigate to correct directory and run Python script
        run: |
          cd $GITHUB_WORKSPACE/scripts
          echo "Current directory after cd:"
          pwd
          ls -alh  # List files to confirm the script is present
          source venv/bin/activate  # Activate the virtual environment
          python merge_epg_cs.py update update || exit 1

      - name: Check for changes (optional)
        run: |
          git status
          git diff --exit-code || echo "Changes detected"

      - name: Commit changes (if any)
        run: |
          export TZ=America/New_York  # Set timezone to Eastern Time
          echo "Checking for changes to commit..."
          git add .
          git commit -m "workflow_dispatch commit: EPG file updated on $(date +'%b %d %Y %H:%M:%S ET')" || echo "No changes to commit"
          if [ "$(git status --porcelain)" ]; then
              echo "Changes detected. Pushing to main branch."
              git push origin main
          else
              echo "No changes to push"
          fi
