name: EPG Update

on:
  schedule:
    - cron: '5 5,17 * * *'  # 1:05 AM ET and 1:05 PM ET every day

jobs:
  scheduled_task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print working directory
        run: |
          echo "Current directory:"
          pwd

      - name: List directory contents
        run: |
          echo "Listing files in current directory:"
          ls -alh

      - name: Navigate to correct directory and run Python script
        run: |
          # Make sure we are in the correct directory
          cd $GITHUB_WORKSPACE/scripts
          echo "Current directory after cd:"
          pwd
          ls -alh  # List files to confirm the script is present
          python3 merge_epg_cs.py update
